### ISSUE TITLE
Loading error?

### ISSUE THREAD

**Issue by madtomic** [BerndiVader/mmCustomSkills26#15]
Using the latest MysticMobs

[16:50:22] [Server thread/INFO]: [mmCustomSkills26] Enabling mmCustomSkills26 v1.2
[16:50:22] [Server thread/INFO]: [mmCustomSkills26] registered ThiefHandlers!
[16:50:22] [Server thread/INFO]: [mmCustomSkills26] Found MythicMobs, registered CustomSkills.
[16:50:22] [Server thread/INFO]: Found MythicMobs, register MythicPlayers.
[16:50:22] [Server thread/INFO]: [mmCustomSkills26] registered MythicPlayers!
[16:50:22] [Server thread/INFO]: [mmCustomSkills26] NaN patch applied!
[16:50:22] [Server thread/INFO]: Register CustomConditions
[16:50:22] [Server thread/INFO]: [mmCustomSkills26] HolographicDisplays support enabled!
[16:50:22] [Server thread/ERROR]: Error occurred while enabling mmCustomSkills26 v1.2 (Is it up to date?)
java.lang.NullPointerException: null
	at com.gmail.berndivader.cachedowners.CachedOwnerHandler.saveCachedOwners(CachedOwnerHandler.java:138) ~[?:?]
	at com.gmail.berndivader.cachedowners.CachedOwnerHandler.<init>(CachedOwnerHandler.java:41) ~[?:?]
	at com.gmail.berndivader.mmcustomskills26.Main.onEnable(Main.java:107) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.2.jar:git-Paper-1209]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.12.2.jar:git-Paper-1209]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [patched_1.12.2.jar:git-Paper-1209]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:386) [patched_1.12.2.jar:git-Paper-1209]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:335) [patched_1.12.2.jar:git-Paper-1209]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) [patched_1.12.2.jar:git-Paper-1209]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) [patched_1.12.2.jar:git-Paper-1209]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) [patched_1.12.2.jar:git-Paper-1209]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:290) [patched_1.12.2.jar:git-Paper-1209]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) [patched_1.12.2.jar:git-Paper-1209]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
[16:50:22] [Server thread/INFO]: [mmCustomSkills26] Disabling mmCustomSkills26 v1.2

**Comment by BerndiVader** [comment]
Hello! Thanks its fixed in the dev build. It happened at first run.
