### ISSUE TITLE
Stun skill problem for 1.13

### ISSUE THREAD

**Issue by CyanBillows** [BerndiVader/mmCustomSkills26#65]
```
[MythicMobsExtension] Task #1190 for MythicMobsExtension v1.320-SNAPSHOT generated an exception
java.lang.NullPointerException: null
        at com.gmail.berndivader.mythicmobsext.mechanics.StunMechanic$1.run(StunMechanic.java:74) ~[?:?]
        at org.bukkit.craftbukkit.v1_13_R1.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.13.jar:git-Paper-160]
        at org.bukkit.craftbukkit.v1_13_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[patched_1.13.jar:git-Paper-160]
        at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:979) ~[patched_1.13.jar:git-Paper-160]
        at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:428) ~[patched_1.13.jar:git-Paper-160]
        at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:915) ~[patched_1.13.jar:git-Paper-160]
        at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:813) ~[patched_1.13.jar:git-Paper-160]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
```

**Comment by BerndiVader** [comment]
Hello! mme's nms code isnt compatible with 1.13 or 1.13.1, it supports 1.12.2 and 1.13.2

**Comment by CyanBillows** [comment]
> nms

Well,anyhow,thanks for your work,it's really a good plugin.:D
