### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by 0000Artur0000** [BerndiVader/mmCustomSkills26#69]
[00:55:44] [Server thread/ERROR]: Error occurred while enabling MythicMobsExtension v1.440-SNAPSHOT (Is it up to date?)
java.lang.NoClassDefFoundError: com/sk89q/worldedit/Vector
	at com.gmail.berndivader.mythicmobsext.compatibility.worldguard.Reflections.load_classes(Reflections.java:98) ~[?:?]
	at com.gmail.berndivader.mythicmobsext.compatibility.worldguard.Reflections.<clinit>(Reflections.java:49) ~[?:?]
	at com.gmail.berndivader.mythicmobsext.compatibility.worldguard.WorldGuardFlag.<init>(WorldGuardFlag.java:21) ~[?:?]
	at com.gmail.berndivader.mythicmobsext.Main.onEnable(Main.java:120) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.14.4.jar:git-Paper-176]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.14.4.jar:git-Paper-176]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[patched_1.14.4.jar:git-Paper-176]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467) ~[patched_1.14.4.jar:git-Paper-176]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381) ~[patched_1.14.4.jar:git-Paper-176]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:474) ~[patched_1.14.4.jar:git-Paper-176]
	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:290) ~[patched_1.14.4.jar:git-Paper-176]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:870) ~[patched_1.14.4.jar:git-Paper-176]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldedit.Vector
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_222]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:139) ~[patched_1.14.4.jar:git-Paper-176]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:85) ~[patched_1.14.4.jar:git-Paper-176]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_222]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_222]
	... 13 more

**Comment by BerndiVader** [comment]
fixed. its now compatible with 7.0.1 and <7.0
