### ISSUE TITLE
Error in 1.14.4 java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by quorn23** [BerndiVader/mmCustomSkills26#72]
`[19:53:14] [Server thread/INFO]: [MythicMobsExtension] Javascripts reloaded.
[19:53:14] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[19:53:14] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[19:53:14] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[19:53:14] [Server thread/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[19:53:14] [Server thread/WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[19:53:14] [Server thread/WARN]: 	at com.gmail.berndivader.mythicmobsext.conditions.CustomConditions.registerCondition(CustomConditions.java:42)
[19:53:14] [Server thread/WARN]: 	at com.gmail.berndivader.mythicmobsext.conditions.CustomConditions.onMythicMobsConditionsLoadEvent1(CustomConditions.java:28)
[19:53:14] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1083.execute(Unknown Source)
[19:53:14] [Server thread/WARN]: 	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[19:53:14] [Server thread/WARN]: 	at org.bukkit.plugin.EventExecutor$$Lambda$2514.0000000031240A80.execute(Unknown Source)
[19:53:14] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[19:53:14] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[19:53:14] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545)
[19:53:14] [Server thread/WARN]: 	at io.lumine.xikage.mythicmobs.skills.conditions.all.CustomCondition.lambda$new$207(CustomCondition.java:29)
[19:53:14] [Server thread/WARN]: 	at io.lumine.xikage.mythicmobs.skills.conditions.all.CustomCondition$$Lambda$4192.00000000046EB9E0.run(Unknown Source)
[19:53:14] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84)
[19:53:14] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452)
[19:53:14] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1148)
[19:53:14] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417)
[19:53:14] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1075)
[19:53:14] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:919)
[19:53:14] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:819)
[19:53:14] [Server thread/WARN]: Caused by: java.lang.NoSuchFieldError: com/gmail/berndivader/mythicmobsext/conditions/AbstractCustomCondition.actionVar
[19:53:14] [Server thread/WARN]: 	at com.gmail.berndivader.mythicmobsext.conditions.AbstractCustomCondition.<init>(AbstractCustomCondition.java:32)
[19:53:14] [Server thread/WARN]: 	at com.gmail.berndivader.mythicmobsext.conditions.MobsInRadiusCondition.<init>(MobsInRadiusCondition.java:30)
[19:53:14] [Server thread/WARN]: 	... 21 more
`

Using the latest MM prem (4.7) and latest MME (MythicMobsExtension v1.440-SNAPSHOT)
Edit: a little bit easier readable https://pastebin.com/UEXh3fYu

**Comment by BerndiVader** [comment]
Hello! As long as MythicMobs 4.7+ isnt free you need to use https://github.com/BerndiVader/MythicMobsExtension/releases

**Comment by quorn23** [comment]
Not sure why you're closing this, as this is indeed what i'm using. That's why i'm reporting it.

**Comment by BerndiVader** [comment]
i reopen it. if the link i suggested dont  work,. post the startup or exception tree.
