### ISSUE TITLE
mm extension startup error with mm 4.8 and 4.9

### ISSUE THREAD

**Issue by espen96** [BerndiVader/mmCustomSkills26#74]
`[22:10:48 INFO]: [MythicMobsExtension] Enabling MythicMobsExtension v1.441a-SNAPSHOT
[22:10:48 ERROR]: An unexpected error occurred initializing Magic
java.lang.NoSuchMethodException: net.minecraft.server.v1_15_R1.NBTTagString.<init>(java.lang.String)
        at java.lang.Class.getConstructor0(Unknown Source) ~[?:1.8.0_221]
        at java.lang.Class.getConstructor(Unknown Source) ~[?:1.8.0_221]
        at com.gmail.berndivader.mythicmobsext.compatibilitylib.NMSUtils.initialize(NMSUtils.java:493) ~[?:?]
        at com.gmail.berndivader.mythicmobsext.NMS.NMSUtils.initialize(NMSUtils.java:76) ~[?:?]
        at com.gmail.berndivader.mythicmobsext.Main.onEnable(Main.java:101) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.1.jar:git-Paper-33]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.15.1.jar:git-Paper-33]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[patched_1.15.1.jar:git-Paper-33]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:468) ~[patched_1.15.1.jar:git-Paper-33]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:382) ~[patched_1.15.1.jar:git-Paper-33]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:481) ~[patched_1.15.1.jar:git-Paper-33]
        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:290) ~[patched_1.15.1.jar:git-Paper-33]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:884) ~[patched_1.15.1.jar:git-Paper-33]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
[22:10:48 INFO]: [DiscordSRV] [JDA] Login Successful!
[22:10:48 INFO]: [MythicMobsExtension] registered mechanics!
[22:10:48 INFO]: [MythicMobsExtension] registered conditions!
[22:10:48 INFO]: [MythicMobsExtension] registered targeters!
[22:10:48 INFO]: [MythicMobsExtension] using WorldGuard
[22:10:48 INFO]: [MythicMobsExtension] using HolograpicDisplays
[22:10:48 INFO]: [MythicMobsExtension] using ProtocolLib`

**Comment by mibby** [comment]
@BerndiVader Also able to confirm this error with MMExtension dev 347 and the latest dev build of mythic mobs on 1.15. :(

```
[20:00:41] [Server thread/INFO]: [MythicMobs] ------------------------------------------------
[20:00:41] [Server thread/INFO]: [MythicMobs] + Loading MythicArtifacts for Bukkit
[20:00:41] [Server thread/INFO]: [MythicMobs] ------------------------------------------------
[20:00:41] [Server thread/INFO]: [MythicMobs] Started up bStats Metrics
[20:00:41] [Server thread/INFO]: [MythicMobsExtension] Enabling MythicMobsExtension v1.441a-SNAPSHOT
[20:00:41] [Server thread/ERROR]: An unexpected error occurred initializing Magic
java.lang.NoSuchMethodException: net.minecraft.server.v1_15_R1.NBTTagString.<init>(java.lang.String)
	at java.lang.Class.getConstructor0(Class.java:3082) ~[?:1.8.0_232]
	at java.lang.Class.getConstructor(Class.java:1825) ~[?:1.8.0_232]
	at com.gmail.berndivader.mythicmobsext.compatibilitylib.NMSUtils.initialize(NMSUtils.java:493) ~[?:?]
	at com.gmail.berndivader.mythicmobsext.NMS.NMSUtils.initialize(NMSUtils.java:76) ~[?:?]
	at com.gmail.berndivader.mythicmobsext.Main.onEnable(Main.java:101) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[paperclip.jar:git-Purpur-397]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[paperclip.jar:git-Purpur-397]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[paperclip.jar:git-Purpur-397]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:468) ~[paperclip.jar:git-Purpur-397]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:382) ~[paperclip.jar:git-Purpur-397]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:482) ~[paperclip.jar:git-Purpur-397]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:299) ~[paperclip.jar:git-Purpur-397]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:886) ~[paperclip.jar:git-Purpur-397]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
[20:00:41] [Server thread/INFO]: [MythicMobsExtension] enabled externals
[20:00:41] [Server thread/INFO]: [MythicMobsExtension] registered mechanics!
[20:00:41] [Server thread/INFO]: [MythicMobsExtension] registered conditions!
[20:00:41] [Server thread/INFO]: [MythicMobsExtension] registered targeters!
[20:00:41] [Server thread/INFO]: [MythicMobsExtension] enabled javascript!
[20:00:41] [Server thread/INFO]: [MythicMobsExtension] using MythicPlayers
[20:00:41] [Server thread/INFO]: [MythicMobsExtension] using WorldGuard
[20:00:41] [Server thread/INFO]: [MythicMobsExtension] using HolograpicDisplays
[20:00:41] [Server thread/INFO]: [MythicMobsExtension] using ProtocolLib
[20:00:41] [Server thread/INFO]: [MythicMobsExtension] using Quests
```
