### ISSUE TITLE
Java.lang.NoClassDefFoundError: me/blackvein/quests/Quests

### ISSUE THREAD

**Issue by benevolent2012** [BerndiVader/mmCustomSkills26#83]
`[23:19:58 ERROR]: Error occurred while enabling MythicMobsExtension v1.557-SNAPSHOT (Is it up to date?)                                           
java.lang.NoClassDefFoundError: me/blackvein/quests/Quests                                                                                        
        at com.gmail.berndivader.mythicmobsext.compatibility.quests.QuestsSupport.<clinit>(QuestsSupport.java:27) ~[?:?]                          
        at com.gmail.berndivader.mythicmobsext.Main.onEnable(Main.java:136) ~[?:?]                                                                
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.1.jar:git-Paper-136]                                  
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.1.jar:git-Paper-136]                            at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.1.jar:git-Paper-136]                           at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:500) ~[patched_1.16.1.jar:git-Paper-136]                             at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:414) ~[patched_1.16.1.jar:git-Paper-136]                            at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:471) ~[patched_1.16.1.jar:git-Paper-136]                          at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:241) ~[patched_1.16.1.jar:git-Paper-136]                               at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:941) ~[patched_1.16.1.jar:git-Paper-136]                                  at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-136]                         at java.lang.Thread.run(Thread.java:834) [?:?]                                                                                            
Caused by: java.lang.ClassNotFoundException: me.blackvein.quests.Quests                                                                           
        at java.net.URLClassLoader.findClass(URLClassLoader.java:471) ~[?:?]                                                                      
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:171) ~[patched_1.16.1.jar:git-Paper-136]                             at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.16.1.jar:git-Paper-136]                     
        at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]                                                                           
        at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]                                                                           
        ... 12 more     `

**Comment by benevolent2012** [comment]
Full MythicMobsExtension enable to disable console log

https://pastebin.com/TEQsqFG8
#
