### ISSUE TITLE
Console Spam

### ISSUE THREAD

**Issue by MonzterDev** [BerndiVader/mmCustomSkills26#89]
Just updated to the latest Dev Build and keep getting this in my Logs every few seconds.

`[02:44:21 WARN]: [MythicMobsExtension] Plugin MythicMobsExtension v1.737b-SNAPSHOT generated an exception while executing task 2814
java.lang.ClassCastException: class java.util.concurrent.ConcurrentHashMap$EntryIterator cannot be cast to class com.gmail.berndivader.mythicmobsext.utils.Utils$AsyncIteratory (java.util.concurrent.ConcurrentHashMap$EntryIterator is in module java.base of loader 'bootstrap'; com.gmail.berndivader.mythicmobsext.utils.Utils$AsyncIteratory is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @40f1a305)
	at com.gmail.berndivader.mythicmobsext.utils.Utils$MetaRunner$1.run(Utils.java:786) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.3.jar:git-Purpur-805]
	at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58) ~[patched_1.16.3.jar:git-Purpur-805]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.3.jar:git-Purpur-805]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
`

**Comment by Keeg-Turner** [comment]
As mentioned elsewhere, I am also experiencing this issue. Here is my timings report if needed: https://timings.pl3x.net/?id=f0b06f63e61647479be6761cd8767177
