### ISSUE TITLE
Spigot 1.14.4 Console spam, Mob's skill not working.

### ISSUE THREAD

**Issue by thaithien1** [BerndiVader/mmCustomSkills26#90]
[01:43:33] [Craft Scheduler Thread - 14/WARN]: [MythicMobsExtension] Plugin MythicMobsExtension v1.737b-SNAPSHOT generated an exception while executing task 292
java.lang.ClassCastException: java.util.HashMap$EntryIterator cannot be cast to com.gmail.berndivader.mythicmobsext.utils.Utils$AsyncIteratory
        at com.gmail.berndivader.mythicmobsext.utils.Utils$MetaRunner$1.run(Utils.java:786) ~[MythicMobsExtension-1.737b-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot1144.jar:git-Spigot-cbd1a1b-009d8af]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot1144.jar:git-Spigot-cbd1a1b-009d8af]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_271]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_271]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]

**Comment by BerndiVader** [comment]
Hi! a few minutes ago, i pushed an update for issue #89. I think it should fix your issue too.
