### ISSUE TITLE
[Bug] Support for MC 1.17.1 and MM 5.x

### ISSUE THREAD

**Issue by fnrcum** [BerndiVader/mmCustomSkills26#93]
I just tried out Paper 1.17 with MM 5.x dev build and noticed these errors

```ps1
[16:59:06 INFO]: [MythicMobsExtension] Enabling MythicMobsExtension v1.739-SNAPSHOT
[16:59:06 ERROR]: [MythicMobsExtension] An unexpected error occurred initializing Magic
java.lang.ClassNotFoundException: net.minecraft.server.v1_17_R1.Block
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:146) ~[patched_1.17.1.jar:git-Paper-90]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[patched_1.17.1.jar:git-Paper-90]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        at com.gmail.berndivader.mythicmobsext.compatibilitylib.NMSUtils.fixBukkitClass(NMSUtils.java:1746) ~[?:?]
        at com.gmail.berndivader.mythicmobsext.compatibilitylib.NMSUtils.initialize(NMSUtils.java:449) ~[?:?]
        at com.gmail.berndivader.mythicmobsext.NMS.NMSUtils.initialize(NMSUtils.java:70) ~[?:?]
        at com.gmail.berndivader.mythicmobsext.Main.onEnable(Main.java:98) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.17.1.jar:git-Paper-90]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Paper-90]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Paper-90]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.17.1.jar:git-Paper-90]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.17.1.jar:git-Paper-90]
        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:639) ~[patched_1.17.1.jar:git-Paper-90]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[patched_1.17.1.jar:git-Paper-90]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1126) ~[patched_1.17.1.jar:git-Paper-90]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-90]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[16:59:06 WARN]: java.lang.ClassNotFoundException: net.minecraft.server.v1_17_R1.IChatBaseComponent$ChatSerializer
[16:59:06 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:146)
[16:59:06 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
[16:59:06 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
[16:59:06 WARN]:        at com.gmail.berndivader.mythicmobsext.compatibilitylib.NMSUtils.fixBukkitClass(NMSUtils.java:1746)
[16:59:06 WARN]:        at com.gmail.berndivader.mythicmobsext.NMS.NMSUtils.initialize(NMSUtils.java:72)
[16:59:06 WARN]:        at com.gmail.berndivader.mythicmobsext.Main.onEnable(Main.java:98)
[16:59:06 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[16:59:06 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[16:59:06 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[16:59:06 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:518)
[16:59:06 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:432)
[16:59:06 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:639)
[16:59:06 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:306)
[16:59:06 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1126)
[16:59:06 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[16:59:06 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[16:59:06 ERROR]: Error occurred while enabling MythicMobsExtension v1.739-SNAPSHOT (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Method.invoke(Object, Object[])" because "com.gmail.berndivader.mythicmobsext.NMS.NMSUtils.class_CraftServer_getEntityMetadataStoreMethod" is null
        at com.gmail.berndivader.mythicmobsext.NMS.NMSUtils.getEntityMetadataMap(NMSUtils.java:458) ~[?:?]
        at com.gmail.berndivader.mythicmobsext.utils.Utils$MetaRunner.<init>(Utils.java:777) ~[?:?]
        at com.gmail.berndivader.mythicmobsext.utils.Utils.<init>(Utils.java:171) ~[?:?]
        at com.gmail.berndivader.mythicmobsext.Main.onEnable(Main.java:99) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.17.1.jar:git-Paper-90]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Paper-90]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Paper-90]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.17.1.jar:git-Paper-90]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.17.1.jar:git-Paper-90]
        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:639) ~[patched_1.17.1.jar:git-Paper-90]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[patched_1.17.1.jar:git-Paper-90]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1126) ~[patched_1.17.1.jar:git-Paper-90]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-90]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[16:59:06 INFO]: [MythicMobsExtension] Disabling MythicMobsExtension v1.739-SNAPSHOT
```

**Comment by h266579110** [comment]
Same here.
Paper 1.18.1 with MM 4.14.2
